### ISSUE TITLE
Hyphen in lib name causes new lcmtypes.cmake to not build lib properly

### ISSUE THREAD

**Issue by wxmerkt** [openhumanoids/bot_core_lcmtypes#12]
These work:
- `C_LIBNAME "lcmtypes_bot2-core_"`
- `C_LIBNAME "lcmtypes_bot2-core."`
- `C_LIBNAME "lcmtypes_bot2core"`
- `C_LIBNAME "lcmtypes_bot2_core"`

This does not (but is **_required**_ for backwards compatibility with current use cases):
- `C_LIBNAME "lcmtypes_bot2-core"`

because it is classed as a UTILITY:

```
-- Configuring done
CMake Internal Error (please report a bug) in CMakeLists.txt:
  cmTarget::GetOutputInfo called for lcmtypes_bot2-core which has type
  UTILITY

make[1]: *** [cmake_check_build_system] Aborted (core dumped)
make: *** [all] Error 2
```

Hence, we should avoid dashes near the end of a variable name (and that's why there's the sanitisation).

I'll open this issue here for discussion and keeping track. For now oh-distro and valkyrie-lcm-distro will rely on reverted CMakeLists

Cf.
- https://cmake.org/gitweb?p=cmake.git;a=commitdiff;h=7e9f908e via https://cmake.org/Bug/view.php?id=15657
- http://marc.info/?l=kde-commits&m=136994742310685

**Comment by wxmerkt** [comment]
Hi @jhoare 
Your pull request #3 brought in an updated lcmtypes.cmake and pods.cmake to support Windows builds. This has broken the ability to have the C_LIBNAME be `lcmtypes_bot2-core` as this string is interpreted as a utility. Hence, a lot of our Linux-based builds are broken (libbot, oh-distro, etc.). I've started to revert locally and port the changes over step by step; the new pods.cmake is fine, the lcmtypes.cmake is not (it throws at the [pods_install_libraries](https://github.com/openhumanoids/bot_core_lcmtypes/blob/master/cmake/lcmtypes.cmake#L193) line).

Do you have any suggestion on how to best address it in CMake that `lcmtypes_bot2-core` can be used as the C_LIBNAME/is not interpreted as a utility?

Thanks!

**Comment by jhoare** [comment]
Hi @iamwolf, is there a simple, relatively minimal setup where I can replicate this issue? It seems to be building on my system with drake. I'm happy to try to get this resolved and working, and I apologize for the issues it's caused.

**Comment by jhoare** [comment]
Would creating a new library e.g. `C_LIBNAME "lcmtypes_bot2_core"` and create a symbolic link on non-windows systems with the old name address the issue?

**Comment by wxmerkt** [comment]
Hi @jhoare 
Thanks for looking into it. The easiest way is to clone this repository, make, and `ls build/lib`. The name of the library needs to be `lcmtypes_bot2-core`. With the new lcmtypes.cmake you can set it via C_LIBNAME in the top-level CMakeLists.txt (currently the lcmtypes_ and name is flipped, so that needs to be changed).

We'd like to do it without having to put a symlink in manually in all repositories that assume the status quo. If CMake creates it, fine by me.

Thanks

**Comment by jhoare** [comment]
Yes, I was suggesting having cmake create a symbolic link. So are your other programs not using the pkg-config output to get the library name, and instead have the library name hard coded? 

I ask because I have found an issue with the generation of the pkg-config file in cmake/lcmtypes.cmake

#14 fixes the aforementioned pkg-config issue.

**Comment by jhoare** [comment]
@iamwolf  Is this still an issue? Can your other projects not use pkg-config to get the correct library name?

**Comment by wxmerkt** [comment]
Yes, this is still an issue as the name in the pkg-config file also changed. We previously used pkg-config as well, but the name for the library changed - from lcmtypes_bot2-core to bot2_core_lcmtypes.

**Comment by jhoare** [comment]
Couldn't you just update the name of the library on the packages that are using this package? (Apologies if this is obvious, I'm not aware precisely how this package is used, especially outside of drake.)

**Comment by patmarion** [comment]
It's used in many modules of the openhumanoids stack, it is a core library.  I think we'd rather not change the name of a core library without a good reason.  (Sorry, I haven't been following along with this thread, so I'm not sure what motivated the library name change, just chiming in :)

**Comment by wxmerkt** [comment]
@patmarion The library name changed due to an updated lcmtypes.cmake that was introduced in #3. It is incompatible with setting the libname back via C_LIBNAME as this causes CMake to interpret the underlying string as a utility which cannot be set as an output filename. The current master of this repository is thus broken for us and we are using a fixed fork that I've created.

**Comment by patmarion** [comment]
I assume lcmtypes.cmake was updated to fix a bug.  Was it not possible to fix the bug without the side effect of breaking the library name definition?

**Comment by jhoare** [comment]
Alright, let me look into this further and try to figure out how to get it working while retaining the original name.

**Comment by jhoare** [comment]
@patmarion the change was largely to get it all building in windows. The library change was unintended, and looking back at the diff I don't see a place where I explicitly changed the name.

**Comment by wxmerkt** [comment]
Old: https://github.com/openhumanoids/bot_core_lcmtypes/pull/3/files#diff-6140331a6a95fa667b3b8c93b94209d3L137

New: https://github.com/openhumanoids/bot_core_lcmtypes/pull/3/files#diff-6140331a6a95fa667b3b8c93b94209d3R163

**Comment by bradking** [comment]
The CMake Internal Error problem occurs when one sets the same `C_LIBNAME` and `JARNAME` in a call to `lcmtypes_build`.  This causes it to essentially do

```
add_library(foo ...) # C_LIBNAME
install(TARGETS foo ...)
....
add_custom_target(foo ...) # JARNAME
```

CMake gets confused because it then thinks you're trying to install a custom target instead of the library.  Normally CMake would reject the duplicate target name but `cmake/lcmtypes.cmake` is setting `CMP0002` to OLD which disables that diagnostic.  CMake should be fixed to not crash in this case, but also lcmtypes should be fixed to not set any policies to OLD.

Projects should never set CMake policies to OLD explicitly except as a quick fix in a maintenance branch.  Otherwise they should always be ported to use NEW behavior.  This is explained in the [cmake-policies(7)](https://cmake.org/cmake/help/v3.5/manual/cmake-policies.7.html) manual.

**Comment by bradking** [comment]
One approach that can be used to support the same value in both C_LIBNAME and JARNAME is to teach lcmtypes_build_c to use a different target name but then set the [OUTPUT_NAME](https://cmake.org/cmake/help/v3.5/prop_tgt/OUTPUT_NAME.html) target property to the actual name desired for the file on disk.  This will avoid duplicate logical target names in CMake while producing the desired file names on disk.

**Comment by jhoare** [comment]
Thanks @bradking, that was helpful. @wxmerkt PTAL at #15 and see if this resolves the issue.

**Comment by wxmerkt** [comment]
Thanks @bradking and @jhoare - this seems to resolve the issue :+1:
