### ISSUE TITLE
bot_core_lcmtypes master cmake is still broken

### ISSUE THREAD

**Issue by mauricefallon** [openhumanoids/bot_core_lcmtypes#16]
I merged https://github.com/openhumanoids/bot_core_lcmtypes/pull/15 . It makes the right lcmtypes library but I'm having problems when using it will one of my other projects:
https://github.com/ipab-slmc/pronto-distro/

I have 023387b1dc071155f898cca5730cad9b88ec6925 at the last fully working rev.

Will investigate

**Comment by wxmerkt** [comment]
Closing as new master now has full CMake'ified build system
