### ISSUE TITLE
bot_core_lcmtypes_export.h is not installed

### ISSUE THREAD

**Issue by patmarion** [openhumanoids/bot_core_lcmtypes#27]
Results in build errors such as:

<pre>
In file included from /Users/pat/source/director/build/src/lcmtypes-rlg-build/lcmtypes/robotlocomotion_grasp_transition_state_t.h:19:
/Users/pat/source/director/build/install/include/lcmtypes/bot_core_position_3d_t.h:10:10: fatal error: 'bot_core_lcmtypes_export.h' file not found
#include "bot_core_lcmtypes_export.h"
         ^
1 error generated.
</pre>

I am using lcm/master and bot_core_lcmtypes/master.  The export header is generated in the bot_core_lcmtypes binary dir, but not installed anywhere that I can find.

/CC @wxmerkt @mwoehlke-kitware

**Comment by wxmerkt** [comment]
@mwoehlke-kitware Can you please take a look at this?

**Comment by mwoehlke-kitware** [comment]
Oops :smile::

``` diff
diff --git a/lcmtypes/CMakeLists.txt b/lcmtypes/CMakeLists.txt
index ac933bf..253b2fc 100644
--- a/lcmtypes/CMakeLists.txt
+++ b/lcmtypes/CMakeLists.txt
@@ -70,6 +70,7 @@ target_include_directories(lcmtypes_bot2-core-cpp INTERFACE
   $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>)

 lcm_install_headers(
+  ${CMAKE_CURRENT_BINARY_DIR}/bot_core_lcmtypes_export.h
   ${c_install_headers}
   ${cpp_install_headers}
   DESTINATION include/lcmtypes
```

(The tutorial in LCM is up to date, but it's easy to forget this when adding exports to an existing project.)

**Comment by patmarion** [comment]
Ok, I'll open a PR to fix this, and the same one for robotlocomotion/lcmtypes.

**Comment by patmarion** [comment]
(unless you were about to)

**Comment by patmarion** [comment]
Since `c_install_headers` is populated by `lcm_wrap_types()` defined in lcm's lcmUtilities.cmake, seems like that file should be patched to put the export header into the `c_install_headers` list?

**Comment by wxmerkt** [comment]
While we are at it, should we create a `<lcmtypes/bot_core.hpp>` header that has been moved to `<lcmtypes/bot_core/bot_core.hpp>` for better backwards compatibility?

**Comment by patmarion** [comment]
in my builds, it looks like `<lcmtypes/bot_core.hpp>` is generated and installed, and not `<lcmtypes/bot_core/bot_core.hpp>` so unless im confused it seems that incompatibility move has been reverted

**Comment by patmarion** [comment]
nevermind, i see the call to `generate_export_header()` lives in the project's CMakeLists.txt, not lcmUtilities.cmake, so `lcm_wrap_types()` shouldn't be worrying about the export header (unless we decide to move it there)

**Comment by mwoehlke-kitware** [comment]
> Since `c_install_headers` is populated by `lcm_wrap_types()` defined in lcm's lcmUtilities.cmake, seems like that file should be patched to put the export header into the `c_install_headers` list?

IIRC, that was my thought also, but when I looked into doing it, it's more complicated than seems obvious because of the `DESTINATION` and `C_INCLUDE` arguments to `lcm_wrap_types` (see also lcm-proj/lcm#123). Also, because the header is created by `generate_export_header`, not `lcm_wrap_types`, it's possible to generate it somewhere that `lcm_wrap_types` would not be able to correctly deduce.

I _may_ yet patch `lcm_wrap_types` (though, the more I think about it, the less I am inclined to do so), but doing it correctly won't happen "soon", and it would need an option to _not_ add the export header to `C_HEADERS` in case of pathological configurations.

p.s. Another approach (probably the most pedantically correct) is:

``` cmake
list(APPEND c_install_headers
  ${CMAKE_CURRENT_BINARY_DIR}/bot_core_lcmtypes_export.h)
```

This way, `c_install_headers` is "complete", and the separation-of-concerns of `lcm_wrap_types` only putting in the list those headers it actually generates is not violated.

**Comment by mwoehlke-kitware** [comment]
> `generate_export_header()` lives in the project's CMakeLists.txt, not lcmUtilities.cmake, so `lcm_wrap_types()` shouldn't be worrying about the export header (unless we decide to move it there)

TBH, I'd love to combine the two, but `generate_export_header` needs the library to exist first (and having `lcm_wrap_types` also create the library makes it entirely too monolithic; see RobotLocomotion/drake#3426).

**Comment by mwoehlke-kitware** [comment]
> While we are at it, should we create a `<lcmtypes/bot_core.hpp>` header that has been moved to `<lcmtypes/bot_core/bot_core.hpp>` for better backwards compatibility?

I forget; we decided we _do_ want to make that change to where the aggregate header is generated? Or are the affected users already patched? (TBH, I'd somewhat prefer to keep it as is if it isn't a problem; IMHO the current naming makes more sense.)

If this still needs to be addressed, can you please open an issue against LCM?

**Comment by wxmerkt** [comment]
Most affected users are patched - however we are currently maintaining both the legacy and CMake build system as we cannot ask our users to move to CMake'ified LCM that the new build system requires until the bot-spy issue is fixed. Thus to patch all it'd be better to be fully compatible with both systems and create that header even though I like the new convention better as well.

Alright, thanks, have created an issue in LCM :)

**Comment by patmarion** [comment]
resolved by PR https://github.com/openhumanoids/bot_core_lcmtypes/pull/28
